### ISSUE TITLE
missing about link in tree search

### ISSUE THREAD

**Issue by milandv** [p3lab/GetAboutPages#6] opened 2021-01-29 13:52 UTC
Example: https://www.sierraclub.org/take-action  returns "no page found" but there is one on the page. 

Could the issue be: `if (sum(c(is.na(if_not_about(href)), is.na(if_not_about(link_text)))) > 0)` ?

Should that be ` == 0` ?

**Comment by jaeyk** [comment] 2021-02-02 19:27
@milandv I added another unit testing for this under the tree search. My impression is the code is correct. If you change `> 0` to `= 0` it didn't pass the existing test: `expect_equal(class(get_about_page_content("http://www.saltpondscoalition.org/")), "character")` I think that the problem is the `base_url`. For instance, if I try this test `expect_equal(class(get_about_page_content("https://www.sierraclub.org/")), "character")`, it works.

**Comment by jaeyk** [comment] 2021-02-02 19:34
@milandv Check the commit (`572a92b`). I added testing. If it resolved the problem, please close this issue.

**Closed as completed** 2021-02-03 01:21 UTC
Labels: bug
